INSERT INTO tag_categories (category_id, category_name) VALUES
(1, "industry"),
(2, "type"),
(3, "technology"),
(4, "complexity_level"),
(5, "platform_tools"),
(6, "use_case_functionality");


INSERT INTO tags (tag_id, category_id, tag_name) VALUES
(1, 1, "Healthcare"),
(2, 1, "Finance"),
(3, 1, "Manufacturing"),
(4, 1, "Retail"),
(5, 1, "Transportation"),
(6, 1, "Education"),
(7, 1, "Customer Service"),
(8, 1, "Entertainment"),
(9, 1, "Agriculture"),
(10, 1, "Cybersecurity"),
(11, 2, "Robotics"),
(12, 2, "Recommendation Systems"),
(13, 2, "Generative AI"),
(14, 2, "Anomaly Detection"),
(15, 2, "Speech Recognition"),
(16, 2, "Computer Vision"),
(17, 2, "Natural Language Processing"),
(18, 3, "Machine Learning"),
(19, 3, "Deep Learning"),
(20, 3, "Computer Vision"),
(21, 3, "Natural Language Processing"),
(22, 3, "Reinforcement Learning"),
(23, 3, "Edge Computing"),
(24, 3, "Transformers"),
(25, 3, "Neural Networks"),
(26, 4, "Beginner"),
(27, 4, "Intermediate"),
(28, 4, "Advanced"),
(29, 4, "Expert"),
(30, 5, "TensorFlow"),
(31, 5, "PyTorch"),
(32, 5, "OpenVINO"),
(33, 5, "Hugging Face"),
(34, 5, "Keras"),
(35, 5, "Scikit-learn"),
(36, 5, "AWS SageMaker"),
(37, 5, "Google Cloud AI"),
(38, 6, "Real-time Video Processing"),
(39, 6, "Predictive Maintenance"),
(40, 6, "Fraud Detection"),
(41, 6, "Speech-to-Text"),
(42, 6, "Recommendation Engine"),
(43, 6, "Chatbots"),
(44, 6, "Autonomous Systems"),
(45, 6, "Image Recognition"),
(46, 6, "Sentiment Analysis");